"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        constant_storage = {chr(i): 0 for i in range(97, 97 + 26)} # O(1)
        for i in s:
            constant_storage[i] += 1
        for i in t:
            if constant_storage.get(i) == 0:
                return i
            constant_storage[i] -= 1
        return ""


def main():
    s = Solution()
    print(s.findTheDifference("abcd", "abcde"))
    print(s.findTheDifference("", "abcde"))
    print(s.findTheDifference("a", "aa"))


if __name__ == "__main__":
    main()
